# Generated by Django 3.0.6 on 2020-05-20 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_name', models.CharField(max_length=32, verbose_name='Symbol Name')),
                ('company_name', models.CharField(max_length=256, null=True, verbose_name='Company Name')),
                ('last_price', models.IntegerField(blank=True, null=True, verbose_name='Last Price')),
                ('final_price', models.IntegerField(blank=True, null=True, verbose_name='Final Price')),
                ('eps', models.IntegerField(null=True, verbose_name='EPS')),
                ('market_type', models.CharField(choices=[('B1', 'بازار اول بورس'), ('B2', 'بازار دوم بورس'), ('F1', 'بازار اول فرابورس'), ('F1', 'بازار دوم فرابورس'), ('PR', 'بازار پایه قرمز'), ('PO', 'بازار پایه نارنجی'), ('PY', 'بازار پایه زرد')], max_length=2, null=True, verbose_name='Market Type')),
                ('base_volume', models.BigIntegerField(blank=True, null=True, verbose_name='Base Volume')),
                ('average_volume', models.BigIntegerField(blank=True, null=True, verbose_name='Average Volume')),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shares', to='bamzi.Industry', verbose_name='Industry')),
            ],
        ),
        migrations.CreateModel(
            name='UserShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Count')),
                ('basic_price', models.BigIntegerField(blank=True, null=True, verbose_name='Basic Price')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='bamzi.Share')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_shares', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
