# Generated by Django 3.0.6 on 2020-08-25 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bamzi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='absolute_max_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='بیشترین قیمت مطلق'),
        ),
        migrations.AddField(
            model_name='share',
            name='absolute_min_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='کمترین قیمت مطلق'),
        ),
        migrations.AddField(
            model_name='share',
            name='tse_id',
            field=models.CharField(default=1, max_length=64, verbose_name='Tse id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usershare',
            name='buy_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ خرید'),
        ),
        migrations.AddField(
            model_name='usershare',
            name='relative_max_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='بیشترین قیمت نسبی'),
        ),
        migrations.AddField(
            model_name='usershare',
            name='relative_min_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='کمترین قیمت نسبی'),
        ),
        migrations.AddField(
            model_name='usershare',
            name='sell_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ فروش'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(max_length=128, verbose_name='نام صنعت'),
        ),
        migrations.AlterField(
            model_name='share',
            name='average_volume',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='حجم میانگین'),
        ),
        migrations.AlterField(
            model_name='share',
            name='base_volume',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='حجم مبنا'),
        ),
        migrations.AlterField(
            model_name='share',
            name='company_name',
            field=models.CharField(max_length=256, null=True, verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='share',
            name='final_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت پایانی'),
        ),
        migrations.AlterField(
            model_name='share',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shares', to='bamzi.Industry', verbose_name='صنعت'),
        ),
        migrations.AlterField(
            model_name='share',
            name='last_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='آخرین قیمت'),
        ),
        migrations.AlterField(
            model_name='share',
            name='market_type',
            field=models.CharField(choices=[('B1', 'بازار اول بورس'), ('B2', 'بازار دوم بورس'), ('F1', 'بازار اول فرابورس'), ('F2', 'بازار دوم فرابورس'), ('PR', 'بازار پایه قرمز'), ('PO', 'بازار پایه نارنجی'), ('PY', 'بازار پایه زرد')], max_length=2, null=True, verbose_name='نوع بازار'),
        ),
        migrations.AlterField(
            model_name='share',
            name='symbol_name',
            field=models.CharField(max_length=32, verbose_name='نام سهم'),
        ),
        migrations.AlterField(
            model_name='usershare',
            name='basic_price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='سربه\u200cسر'),
        ),
        migrations.AlterField(
            model_name='usershare',
            name='count',
            field=models.IntegerField(verbose_name='تعداد'),
        ),
        migrations.CreateModel(
            name='ShareConvention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convention_date', models.DateField(blank=True, null=True, verbose_name='تاریخ مجمع')),
                ('accumulated_profit', models.IntegerField(default=0, verbose_name='سود انباشته')),
                ('revaluation', models.IntegerField(default=0, verbose_name='تجدید ارزیابی')),
                ('cash_priority', models.IntegerField(default=0, verbose_name='آورده نقدی')),
                ('level', models.SmallIntegerField(choices=[(1, 'مرحله پیشنهاد'), (2, 'مرحله حسابرس'), (3, 'مرحله مجوز'), (4, 'مرحله دعوت'), (5, 'مرحله تصمیمات'), (6, 'مرحله ثبت')], verbose_name='مرحله')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convention', to='bamzi.Share')),
            ],
        ),
    ]
