# Generated by Django 3.0.6 on 2020-05-21 00:50
from django.db import migrations, models

from bamzi.helpers.helpers import csv_to_array, persian_text_normalizer


class Migration(migrations.Migration):

    def load_shares_data(apps, schema_editor):
        share_model = apps.get_model("bamzi", "Share")
        share_model.objects.all().delete()
        all_shares = csv_to_array('all_shares')
        all_company_names = csv_to_array('all_company_names')
        for share in all_shares.values:
            share_name = persian_text_normalizer(share[0])
            bool_company = (persian_text_normalizer(all_company_names['symbol'].iloc[0]) == share_name)
            temp_company = all_company_names[bool_company]
            company_name = ''
            if not temp_company.empty:
                company_name = persian_text_normalizer(temp_company['company'].iloc[0])
            share_obj = share_model(symbol_name=share_name,
                                    company_name=company_name)
            share_obj.save()

    dependencies = [
        ('bamzi', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_shares_data, lambda apps, schema_editor: None)
    ]