# Generated by Django 3.0.6 on 2020-05-21 00:50

from django.db import migrations, models

from bamzi.helpers.helpers import shares_csv_to_array, persian_text_normalizer


class Migration(migrations.Migration):

    def load_shares_data(apps, schema_editor):
        share_model = apps.get_model("bamzi", "Share")
        share_model.objects.all().delete()
        all_shares = shares_csv_to_array()
        for share in all_shares:
            share_obj = share_model(symbol_name=persian_text_normalizer(share))
            share_obj.save()
    dependencies = [
        ('bamzi', '0001_initial'),
    ]


    operations = [
        migrations.AlterField(
            model_name='share',
            name='eps',
            field=models.IntegerField(null=True, verbose_name='EPS'),
        ),
        migrations.RunPython(load_shares_data, lambda apps, schema_editor: None)
    ]