# Generated by Django 3.0.6 on 2020-09-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamzi', '0002_auto_20200825_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershare',
            name='buy_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ خرید'),
        ),
    ]
