# Generated by Django 3.0.6 on 2020-10-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamzi', '0003_auto_20200907_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='sl1',
            field=models.IntegerField(blank=True, null=True, verbose_name='اولین هدف نزول'),
        ),
        migrations.AddField(
            model_name='share',
            name='tp1',
            field=models.IntegerField(blank=True, null=True, verbose_name='اولین هدف صعود'),
        ),
        migrations.AlterField(
            model_name='usershare',
            name='basic_price',
            field=models.BigIntegerField(default=0, verbose_name='سربه\u200cسر'),
            preserve_default=False,
        ),
    ]
