# Generated by Django 3.0.6 on 2020-10-04 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bamzi', '0006_auto_20201004_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecedenceShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True, verbose_name='از تاریخ')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='تا تاریخ')),
                ('convert', models.BooleanField(verbose_name='تبدیل کنیم؟')),
                ('became_convert', models.BooleanField(verbose_name='تبدیل شد؟')),
                ('main_share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precedence_main_share', to='bamzi.Share')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precedence_share', to='bamzi.Share')),
            ],
        ),
        migrations.CreateModel(
            name='UserPrecedenceShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='تعداد')),
                ('done', models.BooleanField(verbose_name='انجام شد')),
                ('precedence_share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='bamzi.PrecedenceShare')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_precedence', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
