# Generated by Django 3.0.6 on 2020-10-09 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bamzi', '0008_auto_20201005_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='share',
            options={'ordering': ['symbol_name']},
        ),
        migrations.AddField(
            model_name='industry',
            name='code',
            field=models.IntegerField(default=0, verbose_name='کد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conventionbenefit',
            name='bank',
            field=models.SmallIntegerField(choices=[(0, 'سجام'), (1, 'رفاه کارگران'), (2, 'ملت'), (3, 'تجارت'), (4, 'صادرات'), (5, 'ملی')], verbose_name='بانک'),
        ),
        migrations.AlterField(
            model_name='conventionbenefit',
            name='share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convention_benefit', to='bamzi.Share', verbose_name='سهم'),
        ),
        migrations.AlterField(
            model_name='precedenceshare',
            name='main_share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precedence_main_share', to='bamzi.Share', verbose_name='سهم اصلی'),
        ),
        migrations.AlterField(
            model_name='precedenceshare',
            name='share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precedence_share', to='bamzi.Share', verbose_name='حق تقدم'),
        ),
        migrations.AlterField(
            model_name='share',
            name='market_type',
            field=models.CharField(choices=[('B1', 'بورس (اول)'), ('B2', 'بورس (دوم)'), ('F1', 'فرابورس (اول)'), ('F2', 'فرابورس (دوم)'), ('PR', 'پایه (قرمز)'), ('PO', 'پایه (نارنجی)'), ('PY', 'پایه (زرد)')], max_length=2, null=True, verbose_name='نوع بازار'),
        ),
    ]
