# Generated by Django 3.0.6 on 2020-10-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamzi', '0010_auto_20201010_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='yesterday_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت دیروز'),
        ),
        migrations.AlterField(
            model_name='userconventionbenefit',
            name='got_it',
            field=models.BooleanField(verbose_name='دریافت شد'),
        ),
    ]
